name: Deployment pipeline

on:
  push:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
    - name: Test Success
        uses: rjstone/discord-webhook-notify@v1
        if: success()
        with:
            severity: info
            details: Test Succeeded!
            webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}