name: Pipeline test

on:
  push:
    branches:
      - main

jobs:
  pipeline_test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: johnbeynon/render-deploy-action
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}