name: Deployment pipeline

on:
  push:
    branches:
      - skip

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: skip in commit messages
        env:
          COMMIT_MESSAGES: ${{ contains( join(github.event.commits.*.message, ', '), '#skip' ) }}
        run: echo "$COMMIT_MESSAGES"
      - name: Bump version and push tag
        if: ${{ contains( join(github.event.commits.*.message, ', '), '#skip' ) == false }}
        uses: anothrNick/github-tag-action@1.61.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch