name: Health Check

on:
  schedule:
    - cron:  '* * * * *'

jobs:
  check_health:
    runs-on: ubuntu-20.04
    steps:
    - name: Check the deployed service URL
      uses: jtalk/url-health-check-action@v3
      with:
        url: https://mypokedex23.fly.dev/version
        follow-redirect: false
        max-attempts: 3
        retry-delay: 5s
